# -*- coding: utf-8 -*-
"""rag_feedback_learning_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12P3enubt2zZoP5aGXIAEk3yT0FBYpfKh
"""

!pip install -q sentence-transformers pandas numpy scikit-learn

import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer, util

documents = [
    "Elon Musk founded SpaceX.",
    "SpaceX works on rockets and space exploration.",
    "Tesla builds electric cars.",
    "Elon Musk is CEO of Tesla."
]

df = pd.DataFrame({"text": documents})

model = SentenceTransformer('all-MiniLM-L6-v2')
doc_embeddings = model.encode(df["text"].tolist())

def retrieve(query, k=2):
    query_embedding = model.encode(query)
    scores = util.cos_sim(query_embedding, doc_embeddings)[0]
    scores = scores.cpu().numpy() if hasattr(scores, "cpu") else np.array(scores)

    top_idx = np.argsort(-scores)[:k]
    return df.iloc[top_idx]

answers = ["Elon Musk", "SpaceX", "Tesla"]
answer_embeddings = model.encode(answers)

def extract_answer(query):
    query_embedding = model.encode(query)
    scores = util.cos_sim(query_embedding, answer_embeddings)[0]
    scores = scores.cpu().numpy() if hasattr(scores, "cpu") else np.array(scores)

    return answers[np.argmax(scores)]

feedback_memory = []

def check_feedback(query):
    for q, correct_ans in feedback_memory:
        if q.lower() == query.lower():
            return correct_ans
    return None

def store_feedback(query, predicted, true):
    if predicted.lower() != true.lower():
        feedback_memory.append((query, true))

def feedback_rag(query, true_answer=None):
    print("\n🔹 Query:", query)

    # Step 1: Check past mistakes
    corrected = check_feedback(query)
    if corrected:
        print("♻️ Using learned answer from feedback memory")
        print("✅ Answer:", corrected)
        return corrected

    # Step 2: Normal RAG
    docs = retrieve(query)
    context = " ".join(docs["text"].tolist())

    print("\n📄 Retrieved Context:\n", context)

    answer = extract_answer(query)
    print("\n🤖 Predicted Answer:", answer)

    # Step 3: Learn from mistake
    if true_answer:
        store_feedback(query, answer, true_answer)

    return answer

# First run (may be wrong)
feedback_rag("Who started SpaceX?", "Elon Musk")

# Second run (should improve)
feedback_rag("Who started SpaceX?")

