# -*- coding: utf-8 -*-
"""production_rag_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uaphYfErhYl7Ms0DUlxasOLT8Ob0hKEi
"""

!pip install -q sentence-transformers pandas numpy scikit-learn

import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer, util

documents = [
    "Elon Musk founded SpaceX.",
    "SpaceX works on rockets and space exploration.",
    "Tesla builds electric cars.",
    "Elon Musk is CEO of Tesla."
]

df = pd.DataFrame({"text": documents})

model = SentenceTransformer('all-MiniLM-L6-v2')
doc_embeddings = model.encode(df["text"].tolist())

chat_history = []
feedback_memory = []

def retrieve(query, k=2):
    query_embedding = model.encode(query)
    scores = util.cos_sim(query_embedding, doc_embeddings)[0]
    scores = scores.cpu().numpy() if hasattr(scores, "cpu") else np.array(scores)

    top_idx = np.argsort(-scores)[:k]
    return df.iloc[top_idx], scores[top_idx]

def needs_calculation(query):
    return any(op in query for op in ["+", "-", "*", "/"])

def calculator(query):
    try:
        return str(eval(query))
    except:
        return None

answers = ["Elon Musk", "SpaceX", "Tesla"]
answer_embeddings = model.encode(answers)

def extract_answer(query):
    query_embedding = model.encode(query)
    scores = util.cos_sim(query_embedding, answer_embeddings)[0]
    scores = scores.cpu().numpy() if hasattr(scores, "cpu") else np.array(scores)

    return answers[np.argmax(scores)]

def get_confidence(scores):
    score = float(scores[0])

    if score > 0.7:
        return "High", score
    elif score > 0.5:
        return "Medium", score
    else:
        return "Low", score

def check_feedback(query):
    for q, ans in feedback_memory:
        if q.lower() == query.lower():
            return ans
    return None

def store_feedback(query, predicted, true):
    if true and predicted.lower() != true.lower():
        feedback_memory.append((query, true))

def production_rag(query, true_answer=None):
    print("\n🔹 Query:", query)

    # Feedback check
    learned = check_feedback(query)
    if learned:
        print("♻️ Using learned answer")
        return learned

    # Tool
    calc_result = None
    if needs_calculation(query):
        expr = "".join([c for c in query if c in "0123456789+-*/"])
        calc_result = calculator(expr)
        print("🧮 Tool Output:", calc_result)

    # Retrieval
    docs, scores = retrieve(query)
    print("\n📄 Retrieved:\n", docs)

    # Answer
    answer = extract_answer(query)

    # Confidence
    conf, score = get_confidence(scores)

    print("\n✅ Answer:", answer)
    print("📊 Confidence:", conf, score)

    # Store feedback
    store_feedback(query, answer, true_answer)

    chat_history.append((query, answer))

    return answer

production_rag("Who started SpaceX?", "Elon Musk")
production_rag("Who started SpaceX?")
production_rag("What is 25*4 and which company works on rockets?")

